-- Database Schema for Nudge App (Postgres / Supabase)

-- 1. PROFILES TABLE (Linked to Supabase Auth)
create table public.profiles (
  id uuid references auth.users on delete cascade primary key,
  full_name text,
  purpose text,
  focus_time text,
  needs text[],
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security
alter table public.profiles enable row level security;

-- Profiles Policies
create policy "Users can view their own profile." on public.profiles
  for select using (auth.uid() = id);

create policy "Users can update their own profile." on public.profiles
  for update using (auth.uid() = id);

-- Trigger to auto-create profile row on auth signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name)
  values (new.id, coalesce(new.raw_user_meta_data->>'full_name', 'Nudge User'));
  return new;
end;
$$ language plpgsql security definer;

create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- 2. TASKS TABLE
create table public.tasks (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null default auth.uid(),
  text text not null,
  category text not null,
  urgency text not null,
  effort text not null,
  energy text not null,
  status text not null default 'pending',
  due_date timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security
alter table public.tasks enable row level security;

-- Tasks Policies
create policy "Users can view their own tasks." on public.tasks
  for select using (auth.uid() = user_id);

create policy "Users can insert their own tasks." on public.tasks
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own tasks." on public.tasks
  for update using (auth.uid() = user_id);

create policy "Users can delete their own tasks." on public.tasks
  for delete using (auth.uid() = user_id);


-- 3. HABITS TABLE
create table public.habits (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null default auth.uid(),
  name text not null,
  growth_level integer not null default 1,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security
alter table public.habits enable row level security;

-- Habits Policies
create policy "Users can view their own habits." on public.habits
  for select using (auth.uid() = user_id);

create policy "Users can insert their own habits." on public.habits
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own habits." on public.habits
  for update using (auth.uid() = user_id);

create policy "Users can delete their own habits." on public.habits
  for delete using (auth.uid() = user_id);
